import type { JSX } from 'react';
import { useSearchParams } from 'next/navigation';
import { useState, useEffect} from 'react';
import Head from 'next/head';
import Navbar from '~/components/navbar';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { EpisodeType } from '~/utils/types';
import EpisodeDetails from '~/components/episodeDetails';

export default function Episode(): JSX.Element {
    const searchParams = useSearchParams();
    const id = searchParams.get('id');

    const [item, setItem] = useState<EpisodeType>();
    const [loading, setLoading] = useState<boolean>(false);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchData = async () => {
            try{
                setLoading(true);
                const response = await fetch(
                    `https://rickandmortyapi.com/api/episode/${id}`,
                );

                if (!response.ok) throw new Error('No Character Found');

                const data = await response.json();

                setItem(data);
            } catch (err){
                setError(err instanceof Error ? err.message : 'Unknown error');
            } finally {
                setLoading(false);
            }
        }

        fetchData();
    }, [])

    return (
        <>
            <Head>
				<title>Episode Details</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <main>
                <Navbar />
                <Link href={{}}>
                    <div className="goBackSection">
						<ArrowLeft size={23} />
						<p style={{ fontWeight: 600, fontSize: 'x-large' }}>GO BACK</p>
					</div>
                </Link>
                <EpisodeDetails item={item} />
            </main>

            {loading && <div className="status-msg">Caricamento...</div>}
			{error && <div className="status-msg error">{error}</div>}
        </>
    )
}